export const ds = [
  {
    id: 'n1',
    name: 'FUNDAMENTAL SKILLS',
    title: '',

    children: [
      {
        id: 'n2',
        title: 'How does Internet and websites really work?',
        number: '1',
      },
      {
        id: 'n3',
        title: 'History of the web',
        number: '2',
      },
      { id: 'n4', title: 'HTTP/ HTTPS + FTP', number: '3' },
      { id: 'n5', title: 'Domains (including DNS)', number: '4' },
      { id: 'n6', title: 'Hosting', number: '5' },
      {
        id: 'n7',
        title: 'Setting up your coding environment',
        number: '6',
      },
    ],
  },
  {
    id: 'n8',
    name: 'HTML',
    children: [
      {
        id: 'n9',
        name: 'FUNDAMENTALS',
        number: '1',
        children: [
          { id: 'n10', title: 'parsing HTML files', number: '1.1' },
          { id: 'n11', title: 'History of HTML', number: '1.2' },
          { id: 'n12', title: 'HTML element syntax', number: '1.3' },
          { id: 'n13', title: 'HTML document structure', number: '1.4' },
          { id: 'n14', title: 'HTML document meta data', number: '1.5' },
        ],
      },
      {
        id: 'n15',
        name: 'SEMANTIC HTML',
        number: '2',
        children: [
          {
            id: 'n16',
            title: 'SECTIONS',
            number: '2.1',
            // children: [
            //   { id: 'n17', title: '<body>' },
            //   { id: 'n18', title: '<footer>' },
            //   { id: 'n19', title: '<header>' },
            //   { id: 'n20', title: '<article>' },
            //   { id: 'n21', title: '<section>' },
            //   { id: 'n22', title: '<aside>' },
            //   { id: 'n23', title: '<nav>' },
            //   { id: 'n24', title: '<h1> to <h6>' },
            //   { id: 'n25', title: '<address>' },
            // ],
          },
          {
            id: 'n26',
            title: 'GROUPING ELEMENTS',
            number: '2.2',
            // children: [
            //   { id: 'n27', title: '<div>' },
            //   { id: 'n28', title: '<main>' },
            //   { id: 'n29', title: '<p>' },
            //   { id: 'n30', title: '<hr>' },
            //   { id: 'n31', title: '<figure>' },
            //   { id: 'n32', title: '<figcaption>' },
            //   { id: 'n33', title: '<pre>' },
            //   {
            //     id: 'n31',
            //     title: 'LISTS',
            //     children: [
            //       { id: 'n32', title: '<ul>' },
            //       { id: 'n33', title: '<ol>' },
            //       { id: 'n34', title: '<li>' },
            //       { id: 'n35', title: '<dl>' },
            //       { id: 'n36', title: '<dt>' },
            //       { id: 'n37', title: '<dd>' },
            //     ],
            //   },
            // ],
          },
          {
            id: 'n38',
            title: 'FORMATTING ELEMENTS',
            number: '2.3',
            // children: [
            //   { id: 'n39', title: '<strong>' },
            //   { id: 'n40', title: '<em>' },
            //   { id: 'n41', title: '<mark>' },
            //   { id: 'n42', title: '<q>' },
            //   { id: 'n43', title: '<cite>' },
            //   { id: 'n44', title: '<blockquote>' },
            //   { id: 'n45', title: '<time>' },
            //   { id: 'n46', title: '<del>' },
            //   { id: 'n47', title: '<ins>' },
            //   { id: 'n48', title: '<sub>' },
            //   { id: 'n49', title: '<sup>' },
            //   { id: 'n50', title: '<small>' },
            //   { id: 'n51', title: '<big>' },
            //   { id: 'n52', title: '<code>' },
            //   { id: 'n53', title: '<var>' },
            //   { id: 'n54', title: '<samp>' },
            //   { id: 'n55', title: '<kbd>' },
            //   { id: 'n56', title: '<meter>' },
            //   { id: 'n57', title: '<progress>' },
            //   { id: 'n58', title: '<a>' },
            //   { id: 'n59', title: '<abbr>' },
            //   { id: 'n60', title: '<span>' },
            //   { id: 'n61', title: '<br>' },
            //   { id: 'n62', title: '<b>' },
            // ],
          },
          {
            id: 'n63',
            title: 'LINKS ',
            number: '2.4',
            // children: [
            //   { id: 'n64', title: 'href property' },
            //   {
            //     id: 'n65',
            //     title: 'target property and difference between values',
            //   },
            //   { id: 'n66', title: 'url: absolute and relative' },
            //   { id: 'n67', title: 'attributes and values of links' },
            //   { id: 'n68', title: '<a> and <link>' },
            //   {
            //     id: 'n69',
            //     title: 'navigation to the different parts of the website',
            //   },
            // ],
          },
          {
            id: 'n70',
            title: 'MULTIMEDIA',
            number: '2.5',
            // children: [
            //   { id: 'n71', title: 'image embedding' },
            //   { id: 'n72', title: 'supported image formats' },
            //   { id: 'n73', title: 'alt attribute - why it is so important?' },
            //   { id: 'n74', title: 'loading attribute and lazy load images' },
            //   {
            //     id: 'n75',
            //     title: 'sizing an image - width and height properties',
            //   },
            //   { id: 'n76', title: '<picture> and <source> elements' },
            //   { id: 'n77', title: 'srcset attribute' },
            //   { id: 'n78', title: '<audio> and <video> elements embedding' },
            //   { id: 'n79', title: '<iframe> element' },
            //   { id: 'n80', title: '<canvas> element' },
            //   { id: 'n81', title: '<svg> element' },
            //   { id: 'n82', title: '<map> element' },
            // ],
          },
          {
            id: 'n83',
            title: 'FORMS',
            number: '2.6',
            children: [
              { id: 'n85', title: 'basic input types' },
              { id: 'n86', title: 'handling onchange event' },
              { id: 'n87', title: 'the <label> element and how to use it' },
              {
                id: 'n88',
                title: 'the <button> element and different type values',
              },
              { id: 'n89', title: 'handling onclick event' },
              { id: 'n90', title: 'more input types' },

              { id: 'n92', title: 'the structure of a web form' },
              {
                id: 'n93',
                title: 'form configuration: communicate with server',
              },
              { id: 'n94', title: 'form validation' },
              { id: 'n95', title: 'form submission' },
              { id: 'n96', title: 'form reset' },
            ],
          },
          {
            id: 'n97',
            title: 'EVENTS',
            number: '2.7',
            children: [
              {
                id: 'n98',
                title: 'WINDOW EVENTS',
                // children: [
                //   { id: 'n99', title: 'onload' },
                //   { id: 'n100', title: 'onunload' },
                //   { id: 'n101', title: 'onbeforeunload' },
                //   { id: 'n105', title: 'onresize' },
                //   { id: 'n106', title: 'onscroll' },
                // ],
              },
              {
                id: 'n107',
                title: 'KEYBOARD EVENTS',
                // children: [
                //   { id: 'n108', title: 'onkeydown' },
                //   { id: 'n109', title: 'onkeyup' },
                //   { id: 'n110', title: 'onkeypress' },
                // ],
              },
              {
                id: 'n111',
                title: 'MOUSE EVENTS',
                // children: [
                //   { id: 'n112', title: 'onclick' },
                //   { id: 'n113', title: 'ondblclick' },
                //   { id: 'n114', title: 'onmousedown' },
                //   { id: 'n115', title: 'onmouseup' },
                //   { id: 'n116', title: 'onmousemove' },
                //   { id: 'n117', title: 'onmouseout' },
                // ],
              },
              {
                id: 'n118',
                title: 'GLOBAL EVENTS',
                // children: [
                //   { id: 'n119', title: 'onchange' },
                //   { id: 'n121', title: 'onclose' },
                //   { id: 'n122', title: 'onsubmit' },
                // ],
              },
            ],
          },
          {
            id: 'n123',
            title: 'ACCESSIBILITY',
            number: '2.8',
          },
          {
            id: 'n124',
            title: 'GOOD TO KNOW',
            number: '2.9',
            children: [
              { id: 'n125', title: 'TABLES' },
              { id: 'n126', title: 'SCRIPT + NOSCRIPT' },
              { id: 'n127', title: 'OTHER TAGS - NOT MENTIONS ABOVE' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'n128',
    name: 'CSS',
    children: [
      {
        id: 'n129',
        title: 'BASICS',
        number: '1',
        children: [
          { id: 'n130', title: 'parsing CSS code', number: '1.1' },
          { id: 'n131', title: 'how to add CSS to a website', number: '1.2' },
          { id: 'n132', title: 'CSS syntax', number: '1.3' },
          { id: 'n133', title: 'CSS basic selectors', number: '1.4' },
          {
            id: 'n134',
            title: 'cascade and specifity - resolving conflicts',
            number: '1.5',
          },
          { id: 'n135', title: 'inheritance', number: '1.6' },
          { id: 'n136', title: 'the CSS box model', number: '1.7' },
          { id: 'n137', title: 'sizing CSS elements', number: '1.8' },
          { id: 'n138', title: 'styling CSS elements', number: '1.9' },
          { id: 'n139', title: 'fonts', number: '1.10' },
          { id: 'n140', title: 'images and urls in CSS', number: '1.11' },
          { id: 'n141', title: 'background properties', number: '1.12' },
          { id: 'n142', title: 'opacity/ transparency', number: '1.13' },
          { id: 'n143', title: 'gradients', number: '1.14' },
          { id: 'n144', title: 'shadows', number: '1.15' },
          { id: 'n145', title: 'relative units', number: '1.16' },
        ],
      },
      {
        id: 'n146',
        title: 'ADVANCED',
        number: '2',
        children: [
          {
            id: 'n147',
            title: 'grouping selector: selector list',
            number: '2.1',
          },
          { id: 'n148', title: 'combinator selectors', number: '2.2' },
          { id: 'n149', title: 'pseudo-selectors', number: '2.3' },
          { id: 'n150', title: 'CSS variables', number: '2.4' },
          { id: 'n151', title: 'CSS functions', number: '2.5' },
        ],
      },
      {
        id: 'n152',
        title: 'LAYOUT',
        number: '3',
        // children: [
        //   { id: 'n153', title: 'positioning' },
        //   { id: 'n154', title: 'flexbox' },
        //   { id: 'n155', title: 'grid' },
        //   { id: 'n156', title: 'float' },
        //   { id: 'n157', title: 'centering content' },
        // ],
      },
      {
        id: 'n158',
        title: 'MEDIA QUERIES',
        number: '4',
        // children: [
        //   { id: 'n159', title: 'media query types and syntax' },
        //   { id: 'n160', title: 'mobile first approach' },
        //   { id: 'n161', title: 'breakpoints' },
        // ],
      },
      {
        id: 'n162',
        title: 'TRANSITIONS AND ANIMATIONS',
        number: '5',
        // children: [
        //   { id: 'n163', title: 'transition properties' },
        //   {
        //     id: 'n164',
        //     title: 'transitions with pseudo-elements',
        //   },
        //   {
        //     id: 'n165',
        //     title: 'animations',
        //   },
        //   {
        //     id: 'n166',
        //     title: 'transform property',
        //   },
        // ],
      },
      {
        id: 'n167',
        title: 'METODOLOGIES - BEM, OOCSS, SMACSS',
        number: '6',
      },
      {
        id: 'n168',
        title: 'PREPROCESSORS - SASS + 7+1 PATTERN',
        number: '7',
      },
      {
        id: 'n169',
        title: 'FRAMEWORKS',
        number: '8',
        // children: [
        //   { id: 'n170', title: 'Bootstrap' },
        //   { id: 'n171', title: 'TailwindCSS' },
        //   { id: 'n172', title: 'Other - worth mention' },
        // ],
      },
      {
        id: 'n173',
        title: 'WEB DESIGN RULES',
        number: '9',
      },
      {
        id: 'n174',
        title: 'LAYOUT PATTERNS',
        number: '10',
      },
    ],
  },
];
